#eureka:
#   client:
#     service-url:
#       default-zone: http://localhost:8761/eureka/

spring:
  datasource:
          url: jdbc:postgresql://localhost:5432/usermsdb
          username: postgres
          password: techlab
          driver-class-name: org.postgresql.Driver
jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

